### ISSUE TITLE
Demo improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-cise#1]
- Rename "Representation of Node Colors" to "Node Colors"
- Use a bigger demo graph loaded by default (circ-dogrusoz under samples)
- Remove debugging statements appearing in the Console
- Put a sample layout in the README (should include the legend for cluster colors in upper right for better comprehension)

**Comment by alihanokka** [comment]
All tasks are done
