### ISSUE TITLE
graphml input formt

### ISSUE THREAD

**Issue by xuyu-cam** [iVis-at-Bilkent/cytoscape.js-cise#14]
I have been trying to externally import graph using graphml format file, but failed with various attempts. Just wondering could anyone help to provide a working example of the input  graphml format file, for example, the graph given in the demo. 
Thanks!

**Comment by ugurdogrusoz** [comment]
@xuyu-cam are you interested in importing a graphml file into the demo or to your Cytoscape.js application? in any case the demo uses [this extension](https://github.com/iVis-at-Bilkent/cytoscape.js-graphml) to convert a graphml file into a JSON format that Cytoscape.js accepts.
