### ISSUE TITLE
Cise Layout doesn't work

### ISSUE THREAD

**Issue by FriederHannenheimET** [iVis-at-Bilkent/cytoscape.js-cise#17]
I tried with the demo and a personal project. My browser is Opera. I also tried with Firefox but it doesn't work either. When I exported the json and looked at the nodes the positions show NaN.

**Comment by hasanbalci** [comment]
@FriederHannenheimET  I fixed the [demo](https://ivis-at-bilkent.github.io/cytoscape.js-cise/demo.html) in the master branch, it wasn't using the correct versions of the dependencies, it's working now. If you're using via npm, it should already be working.

**Comment by FriederHannenheimET** [comment]
Jep it works now. Thank you for the quick response!
