### ISSUE TITLE
Nodes outside circles

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-cise#18]
When inner nodes are allowed with a high ratio, we get situations like the following. 
![Screenshot 2021-03-11 145506](https://user-images.githubusercontent.com/3874988/110784705-0d42c500-827b-11eb-9aa7-437898604309.png)
This might be due to two reasons:
- We allow 1 node on the circle. Let's limit the minimum number of nodes to 2 (not allow 1) so such situations don't occur.
- Nodes chosen to be inside circles aren't initially inside the circle creating these problems. Let's make sure that never happens and our invariant is an inner node is always inside the circle.

**Comment by herencalik** [comment]
I limited the oncircle nodes to be at least 2, however, when the oncircle node number is 2 or sometimes even 3, the rotation can change the position/location of the circle and as we do not change the positions of the inner nodes when the circle rotates, they can escape from the inner circular bounds. They get inside again if they can but as this situation happens when the inner part is highly populated, they generally do not.

**Comment by ugurdogrusoz** [comment]
I don't understand how they escape. Don't we constrain them to avoid that?

**Comment by herencalik** [comment]
Yes we constrain them, I have actually found the main problem.

![problemdefimage](https://user-images.githubusercontent.com/25704468/111375375-387c4880-86af-11eb-8f85-2fd527c9f035.jpg)

As we find the inner nodes one-by-one, their initial position is calculated based on the circle's situation at that moment. (That particular node is excluded before this calculation) Therefore, as seen in the figures, even though the first inner node (n17) is placed on to the circle's center (Figure 2), as the circle's radius and center point changes after finding other inner nodes(n19, Figure 3), the node found initially is left outside of inner bounds.

**Comment by ugurdogrusoz** [comment]
Why not re-calculate the geometry of the circle after each new node placed inside the circle if not do placing inside the circle as a batch? Let's discuss.
