### ISSUE TITLE
Demo improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-cise#19]
- [x] 1. Remove highlights button doesn't change background color on mouse over unlike others.
- [x] 2. Max ratio of nodes inside circle can take values more than 1.0 (additional question: what happens if this ratio is 1.0?)

**Comment by ugurdogrusoz** [comment]
2. I can still set this value to be negative or more than 1.0 (by typing the value)

**Comment by herencalik** [comment]
2. Manually entered values cannot be restricted but a pop-up can be shown when an illegal value is entered.

**Comment by ugurdogrusoz** [comment]
2. when the user enters a value greater than 1.0, let's change it to 1.0. Similarly, anything less than 0, change it to 0.

**Comment by ugurdogrusoz** [comment]
2. I can still type 1.5 for instance?
