### ISSUE TITLE
Buggy behavior when Allow Nodes In Circles enabled

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-cise#27]
Sometimes, cluster circles are laid out too wide when `allowNodesInsideCircle` option is enabled. A sample case to reproduce:

- Import following graphml file: [sample.txt](https://github.com/iVis-at-Bilkent/cytoscape.js-cise/files/6539467/sample.txt)
- Enable Allow Nodes In Circles option from Layout Options
- Run layout
The resulting layout is not compact: 
![image](https://user-images.githubusercontent.com/22586369/119503195-5f23c300-bd73-11eb-9134-5a9200fde598.png)

**Comment by herencalik** [comment]
Now when an in-circle node has more than 5 neighbouring on-circle  node, it's displacement is limited using the infinite series similar to one used in Zeno's paradox.
For example, when there are 6 on-circle neighbours of an in-circle node, it's displacement is multiplied by the coefficient:
1 - (0.5 - (0.5)^(6(number of neighbours) - 4)) = 0.5 + (0.5)^(6(number of neighbours) - 4)

**Comment by ugurdogrusoz** [comment]
This might work for smaller large degrees but when we have really high degrees it doesn't.

We investigated this with @hasanbalci and here are our findings:
- We limit the movement of a single node for inner nodes as well but we neglect ([here](https://github.com/iVis-at-Bilkent/cytoscape.js-cise/blob/develop/src/CiSE/CiSENode.js#L90)) to multiply this max displacement value with the current cooling factor. We should do so (similar to how we do it [here](https://github.com/iVis-at-Bilkent/cose-base/blob/0c1a87bb61c7d90acf5240f4541b9dd91e14b188/src/CoSENode.js#L30) in cose layout).

- Secondly, what we want to control high degree nodes is a function that more or less compensates for high degrees. In other words, as the degree of a node increases, the total force on that node should not be increasing arbitrarily. With this scheme, it still does:
![Screenshot 2021-06-18 095250](https://user-images.githubusercontent.com/3874988/122519311-fdc1dd80-d01a-11eb-9b6a-f4dc5184fa2c.png)

If we use a simple function like `4/(number of neighbors)` as `constraintCoefficient`, for any degree (number of neighbors) `d` greater than 4, we still get a total force which is about 4 times an average force and this might work.

**Comment by ugurdogrusoz** [comment]
This looks fixed to me. @hasanbalci please confirm and close if OK.

**Comment by hasanbalci** [comment]
Yes, it's very good now, thanks!
