### ISSUE TITLE
Demo and readme improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-cise#3]
From @maxfranz:
It would be nice to have a demo where the clusters are not predefined.  Maybe this new demo could use one of the built-in clustering algorithms in the core lib.  I suspect this would be a common use-case, and having the demo would avoid people asking questions in the issue tracker.  A simpler alternative to the new demo would be a "How to specify clusters" section in the readme, with a code example.  Again, I don't think this is something that we need right away.

**Comment by ugurdogrusoz** [comment]
We already have an option to apply Markov Clustering on load in our demo now. In addition, we could:
- [x] 1. Describe (with a code segment) how the built-in Markov Clustering can be called to cluster the current graph in the README.
- [x] 2. Add two operations for adding a new cluster for selected and removing selected nodes from any clusters that they are assigned to.

**Comment by ugurdogrusoz** [comment]
2. looks good but let's increasing the paddings around the tooltips
<img width="328" alt="Screen Shot 2021-03-03 at 17 28 53" src="https://user-images.githubusercontent.com/3874988/109820622-3abdbc00-7c46-11eb-8961-8bac8c676abc.png">

**Comment by ugurdogrusoz** [comment]
1. Please remove Demo related pictures and text from README. Demo should be self contained, we shouldn't be explaining what's there in the README. Instead, looking at how it's done in the demo, and **providing code segment(s)**, explain how clustering can be done. In fact, let's implement something like the "i" icon in [this demo](https://ivis-at-bilkent.github.io/cytoscape.js-cosep/demo/demo.html), where we provide quick help to the users. The content could be:

CiSE Demo Help
With this demo, you can:
- Import a graph in GraphML format. If you'd like your graph to be automatically clustered on load, check "Apply Markov Clustering on Load"
- Lay it out using CiSE style
- Right-click on a node to add some random neighbors
- Change current clustering using Add/Remove Cluster buttons
- Adjust layout options (please refer to the API in README for an explanation of these options)

**Comment by herencalik** [comment]
- [x] 3. In the demo, when a graph is imported and a new cluster is added through the add cluster button, current nodes become unclustered.

**Comment by ugurdogrusoz** [comment]
1. we would like to see how the results of Markov clustering can be used when calling CiSE layout in README as well. also, "i" would like better if it's here I think:
![Screenshot 2021-03-11 093204](https://user-images.githubusercontent.com/3874988/110745721-c047fa00-824c-11eb-9a0a-5b6026649510.png)
Finally, now that we have info about adding random neighbors under "i", we should remove it from the bottom (below buttons).
