### ISSUE TITLE
Error on highly varying node dimensions

### ISSUE THREAD

**Issue by herencalik** [iVis-at-Bilkent/cytoscape.js-cise#32]
This problem is caused by the grid implementation. Before the commit 149090623b1f02d7f87d03af3590a9250a2dca81, the root graph's bound was not updated recursively for both in-circle enabled and disabled options as both caused errors when for example there are one enormous node and relatively tiny nodes but now it is updated recursively for the case there is no in circle nodes. The reason recursive update is not done when there are in circle nodes is that it messes up the whole layout. updateBounds() function is in LGraph class of layout-base:
https://github.com/iVis-at-Bilkent/layout-base/blob/3f7549940feef31416cc35ef8256282ebc4d1ecd/src/LGraph.js#L248

**Comment by herencalik** [comment]
Problem can be replicated by enabling incircle nodes with ratio greater than 0.3 using the graph I attached.
[highvarianceinsize.txt](https://github.com/iVis-at-Bilkent/cytoscape.js-cise/files/6795737/highvarianceinsize.txt)

**Comment by ugurdogrusoz** [comment]
@herencalik Thanks, no errors in this case any more. When you say Update Grid is taken to CiSE level, what do you mean? Since grid is used in cose-bilkent and fcose as well, could this create a problem in those layout styles @hasanbalci ?

**Comment by herencalik** [comment]
> 
> 
> @herencalik Thanks, no errors in this case any more. When you say Update Grid is taken to CiSE level, what do you mean? Since grid is used in cose-bilkent and fcose as well, could this create a problem in those layout styles @hasanbalci ?

Update Grid function used in CiSE was that of FDLayout's, which used all nodes in grid calculation. Instead of that, I overrode the updateGrid in CiSE, without changing the original one so there shouldn't be a problem with other layouts.
