### ISSUE TITLE
Cise layout freezes whether uses the last version of layout-base.js

### ISSUE THREAD

**Issue by jfreyreg** [iVis-at-Bilkent/cytoscape.js-cise#40]
Hi I'm trying to use the layout with the last version of layout-base (2.0.1) but the layout doesn't work.

To reproduce:
- Download the demo.html.
- In line 17 replace "https://unpkg.com/layout-base@1.0.2/layout-base.js" for "https://unpkg.com/layout-base/layout-base.js".
- Run the demo and click on 'Run CiSE Layout'.
- Nothing happens.

**Comment by hasanbalci** [comment]
It is because we haven't release the version that supports latest layout-base.js yet. That version is available in the _develop_ branch and when a new version of Cise is released, it will be accessible by npm.

**Comment by ugurdogrusoz** [comment]
@jfreyreg Just released version 2. Please test and close this if things look fine.

**Comment by jfreyreg** [comment]
@ugurdogrusoz Thanks, I have downloaded the zip file source and extracted the cytoscape-cise.js. I want to highlight that the master cytoscape-cise.js was last committed 2 years ago (https://github.com/iVis-at-Bilkent/cytoscape.js-cise/commits/master/cytoscape-cise.js). Despite that, the new release version 2.0.0 was committed 1 hour ago.
