### ISSUE TITLE
How to cluster according to cluster id?

### ISSUE THREAD

**Issue by git4anjali** [iVis-at-Bilkent/cytoscape.js-cise#5]
In the documentation it is written that you can specify clusters property in layout options with a function. But when I am doing the following clusters are not according to clusterid but according to connectivity.

My code:-

const layout = this.cy.layout({ name: 'cise',
            clusters:function(node){return node.clusterID},
            allowNodesInsideCircle:false,
            maxRatioOfNodesInsideCircle:0.1,
            animate:false,
            refresh: 10,
            idealInterClusterEdgeLengthCoefficient: 1.4});
       layout.run();

Could you please let me know the change which I need to have this working.

**Comment by alihanokka** [comment]
Hi,

Since clusterID property is inside the Data element, you need to specify it accordingly. So it should be
`clusters : function( node ){ return node.data('clusterID'); }`

In [here](https://codesandbox.io/s/proud-lake-ce8yi) you can find a simple code I made demonstrating this function. 

Hope this helps!

**Comment by ugurdogrusoz** [comment]
@alihanokka let's provide this example in README

**Comment by git4anjali** [comment]
Thanks @alihanokka , it worked with the way you described.

It was/is not working when I am having clusters property in my options variable as follows, and then run the layout with those options -

```
const layout = this.cy.layout({ name: 'cise', options });
layout.run();
```

```
var options={
    // ClusterInfo can be a 2D array contaning node id's or a function that returns cluster ids.
    // For the 2D array option, the index of the array indicates the cluster ID for all elements in
    // the collection at that index. Unclustered nodes must NOT be present in this array of clusters.
    //
    // For the function, it would be given a Cytoscape node and it is expected to return a cluster id
    // corresponding to that node. Returning negative numbers, null or undefined is fine for unclustered
    // nodes.
    // e.g
    // Array:                                     OR          function(node){
    //  [ ['n1','n2','n3'],                                       ...
    //    ['n5','n6']                                         }
    //    ['n7', 'n8', 'n9', 'n10'] ]
    clusters: function(node) {
      return node.data("clusterID");
    },
    // -------- Optional parameters --------
    // Whether to animate the layout
    // - true : Animate while the layout is running
    // - false : Just show the end result
    // - 'end' : Animate directly to the end result
    animate: false,

    // number of ticks per frame; higher is faster but more jerky
    refresh: 10,

    // Animation duration used for animate:'end'
    animationDuration: undefined,
     ..........// more options
}
```
I am fine with going forward with providing clusters property as follows instead of the above way however just wished to confirm with you if the above should/would not work.

```
 const layout = this.cy.layout({ name: 'cise', clusters: function(node) {
            return node.data("clusterID");
        },options });
 layout.run(); 
```

**Comment by alihanokka** [comment]
Now I understand how the API could be a bit confusing. The [_cy.layout_](http://js.cytoscape.org/#cy.layout) function expects one parameter which is an object consisting of information related to the layout. You can write the object directly as 

```
let layout = cy.layout({ name: 'cise', 
                 clusters:  function(node) { return node.data("clusterID"); },
                 animate: false,
                 nodeSeparation: 15,
                 . . .
});

layout.run();
```
or you can define this object explicitly and then pass it to the function like below.
```
let options = {
               name : "cise",
              clusters: function(node) { return node.data("clusterID");},
              animate: false,
              . . .
}

let layout = cy.layout(options);
layout.run();
```

If you try to do something in between, putting options object inside another object, it won't work.

**Comment by git4anjali** [comment]
Thanks @alihanokka for clearing configuration confusion, it worked as you described!
