### ISSUE TITLE
Max number of nodes inside a circle option

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-cise#9]
When `allowNodesInsideCircle` is true, `maxRatioOfNodesInsideCircle` determines how many nodes are allowed inside each cluster / circle but this option doesn't seem to work properly. In below example we use the default value of this option, which is 0.1. That means we should allow at most 10 percent of the nodes in the circle, which is less than one. Yet we try to put a node inside the circle for clusters with only 6 nodes and they won't fit.
![image](https://user-images.githubusercontent.com/3874988/83752653-8ddfef80-a671-11ea-8c49-03e2bd97b231.png)

**Comment by alihanokka** [comment]
Yes, layout shouldn't put nodes inside the circle in that situations.
